# Generated by Django 6.0.1 on 2026-02-12 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(editable=False, help_text='Auto-generated: BILL/YEAR/NUMBER', max_length=50, unique=True)),
                ('bill_date', models.DateField(help_text='Bill generation date')),
                ('client_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of delivered items before tax', max_digits=12)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal + all taxes', max_digits=12)),
                ('advance_deducted', models.DecimalField(decimal_places=2, default=0, help_text='Advance amount deducted in this bill', max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, help_text='Total amount - advance deducted', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by client', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance', max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(help_text='Reference work order', on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'bills',
                'ordering': ['-bill_number'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(default='PCS', max_length=20)),
                ('ordered_quantity', models.DecimalField(decimal_places=2, help_text='Total quantity in work order', max_digits=10)),
                ('previously_delivered_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity delivered in previous bills', max_digits=10)),
                ('delivered_quantity', models.DecimalField(decimal_places=2, help_text='Quantity delivered in THIS bill', max_digits=10)),
                ('pending_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Remaining quantity after this bill', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per unit', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='delivered_quantity × rate', max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('work_order_item', models.ForeignKey(help_text='Reference to work order item', on_delete=django.db.models.deletion.PROTECT, to='work_orders.workorderitem')),
            ],
            options={
                'verbose_name': 'Bill Item',
                'verbose_name_plural': 'Bill Items',
                'db_table': 'bill_items',
            },
        ),
    ]
