# Generated by Django 6.0.1 on 2026-02-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid by client (sum of all BillPayment rows)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance (net_payable - amount_paid)', max_digits=12),
        ),
    ]
