# Generated by Django 6.0.1 on 2026-03-04 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_amount_paid_alter_bill_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], default='DOMESTIC', help_text='Domestic or International (classification only; all amounts in INR)', max_length=15),
        ),
        migrations.AddField(
            model_name='bill',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat freight / shipping charge added after tax (INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='advance_deducted',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Advance amount deducted in this bill (INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid by client (sum of all BillPayment rows, INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance (net_payable - amount_paid, INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='total_amount + freight_cost - advance_deducted (INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of delivered items before tax (INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal + all taxes (INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='delivered_quantity × rate (INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate per unit (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction (INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, help_text='Remaining balance AFTER this transaction (INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='payment_number',
            field=models.PositiveIntegerField(help_text='Sequential payment number for this bill'),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Cheque number / UTR / SWIFT reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='total_paid_after',
            field=models.DecimalField(decimal_places=2, help_text='Cumulative amount_paid AFTER this transaction (INR)', max_digits=12),
        ),
    ]
