# Generated by Django 6.0.1 on 2026-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_bill_bill_type_bill_freight_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='final_destination',
            field=models.CharField(blank=True, help_text='Final destination', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='importer_address',
            field=models.TextField(blank=True, help_text="Importer's address (for international / export bills)"),
        ),
        migrations.AddField(
            model_name='bill',
            name='port_of_discharge',
            field=models.CharField(blank=True, help_text='Port of discharge', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='port_of_loading',
            field=models.CharField(blank=True, help_text='Port of loading', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='pre_carriage_by',
            field=models.CharField(blank=True, help_text='Pre-carriage by (mode of transport to loading port)', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='terms_of_delivery_payment',
            field=models.CharField(blank=True, help_text='Terms of delivery/payment (e.g. CIF, FOB, DAP, EXW)', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='vessel_flight_no',
            field=models.CharField(blank=True, help_text='Vessel name / flight number', max_length=100),
        ),
    ]
