# Generated by Django 6.0.1 on 2026-05-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_bill_final_destination_bill_importer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', help_text='Currency inherited from work order', max_length=3),
        ),
        migrations.AddField(
            model_name='bill',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='USD to INR rate (1 if INR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='original_cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='original_freight_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Freight cost in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='original_igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='original_net_payable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net payable in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='original_sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='original_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='original_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='billitem',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='billitem',
            name='original_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate in original currency', max_digits=10),
        ),
    ]
