# Generated by Django 6.0.1 on 2026-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_bill_currency_bill_exchange_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='original_cgst_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='original_freight_cost',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='original_igst_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='original_net_payable',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='original_sgst_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='original_subtotal',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='original_total_amount',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='original_amount',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='original_rate',
        ),
        migrations.AlterField(
            model_name='billitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='delivered_quantity × rate', max_digits=12),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate per unit', max_digits=10),
        ),
    ]
