# Generated by Django 6.0.1 on 2026-05-25 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_bill_exchange_rate_and_more'),
        ('inventory', '0005_add_sale_count_and_aging_fields'),
        ('sales', '0007_remove_gst_discount_from_pi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PIBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('bill_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], default='DOMESTIC', max_length=15)),
                ('bill_date', models.DateField()),
                ('client_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=3)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, help_text='INR conversion rate (immutable, copied from PI)', max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount subtracted from total', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='subtotal + GST - discount', max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pi_bills_created', to=settings.AUTH_USER_MODEL)),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pi_bills', to='sales.proformainvoice')),
            ],
            options={
                'db_table': 'pi_bills',
                'ordering': ['-bill_number'],
            },
        ),
        migrations.CreateModel(
            name='PIBillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(default='PCS', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pi_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_bill_items', to='billing.pibill')),
                ('pi_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.proformainvoiceitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'db_table': 'pi_bill_items',
            },
        ),
    ]
