# Generated by Django 6.0.1 on 2026-05-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_pibill_pibillitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billpayment',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='work_order_item',
        ),
        migrations.RemoveField(
            model_name='billpayment',
            name='recorded_by',
        ),
    ]
