# Generated by Django 6.0.1 on 2026-05-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_bill_created_by_remove_bill_work_order_and_more'),
        ('finance', '0003_alter_purchasepayment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
        migrations.DeleteModel(
            name='BillPayment',
        ),
    ]
