version: "3.9"

services:
  server:
    image: ${DOCKER_USERNAME}/energypac_backend:latest
    container_name: energypac_server
    network_mode: host
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2G
