# Generated by Django 6.0.1 on 2026-05-23 06:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g., INR, USD, EUR', max_length=5, unique=True)),
                ('name', models.CharField(help_text='e.g., Indian Rupee, US Dollar', max_length=100)),
                ('symbol', models.CharField(blank=True, help_text='e.g., ₹, $, €', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
    ]
