# Generated by Django 6.0.1 on 2026-03-13 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0004_bill_bill_type_bill_freight_cost_and_more'),
        ('purchase_orders', '0004_purchaseorder_amount_paid_purchaseorder_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.PositiveIntegerField(help_text='Sequential payment number for this bill')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount received in this transaction (INR)', max_digits=12)),
                ('payment_date', models.DateField(help_text='Date on which payment was received from client')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque number / UTR / SWIFT reference', max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('total_paid_after', models.DecimalField(decimal_places=2, help_text='Cumulative amount_paid AFTER this transaction (INR)', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Remaining balance AFTER this transaction (INR)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(help_text='Bill this payment is against', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_payments', to='billing.bill')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Payment',
                'verbose_name_plural': 'Incoming Payments',
                'db_table': 'incoming_payments',
                'ordering': ['bill', 'payment_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.PositiveIntegerField(help_text='Sequential payment number for this PO')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction (INR)', max_digits=12)),
                ('payment_date', models.DateField(help_text='Date on which payment was made to vendor')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='NEFT', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque number / UTR / transaction reference', max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('total_paid_after', models.DecimalField(decimal_places=2, help_text='Cumulative amount_paid AFTER this transaction (INR)', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Remaining balance AFTER this transaction (INR)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(help_text='Purchase Order this payment is against', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payments', to='purchase_orders.purchaseorder')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Payment',
                'verbose_name_plural': 'Purchase Payments',
                'db_table': 'purchase_payments',
                'ordering': ['purchase_order', 'payment_number'],
            },
        ),
    ]
