# Generated by Django 6.0.1 on 2026-05-25 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('sales', '0006_add_gst_discount_conversion_to_pi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advance_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=3)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, help_text='INR conversion rate at time of advance (immutable)', max_digits=10, null=True)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=0, help_text='Amount in INR (amount × conversion_rate, or amount if INR)', max_digits=14)),
                ('amount_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('LC', 'Letter of Credit'), ('TT', 'Telegraphic Transfer'), ('OTHER', 'Other')], default='TT', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULLY_USED', 'Fully Used'), ('REFUNDED', 'Refunded')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proforma_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments', to='sales.proformainvoice')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advance_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('LC', 'Letter of Credit'), ('TT', 'Telegraphic Transfer'), ('OTHER', 'Other')], default='TT', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('total_paid_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_payments', to='sales.proformainvoice')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pi_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pi_payments',
                'ordering': ['proforma_invoice', 'payment_number'],
            },
        ),
    ]
