# Generated by Django 6.0.1 on 2026-05-25 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_advance_payment_and_pi_payment'),
        ('purchase_orders', '0013_add_payment_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasepayment',
            options={'ordering': ['purchase_order', 'payment_number']},
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='amount_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payments', to='purchase_orders.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='total_paid_after',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='IncomingPayment',
        ),
    ]
