# Generated by Django 6.0.1 on 2026-06-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_make_advance_proforma_invoice_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Auto-inherited from PI at advance time', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', help_text='Auto-inherited from PI', max_length=3),
        ),
    ]
