# inventory/views_bulk_upload.py

import openpyxl
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from io import BytesIO

from django.http import HttpResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.parsers import MultiPartParser
from rest_framework import status

from .models import Product


class ProductBulkUploadTemplateView(APIView):
    """
    GET /api/inventory/products/bulk-upload-template/
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        wb = Workbook()
        ws = wb.active
        ws.title = "Products"

        # item_code NOT in template — auto-generated by system
        headers = [
            'item_name',      # required
            'hsn_code',       # optional
            'unit',           # optional, default PCS
            'rate',           # optional, default 0
            'current_stock',  # optional, default 0
            'reorder_level',  # optional, default 0
            'description',    # optional
        ]
        ws.append(headers)

        # Sample rows
        ws.append(['Cement OPC 53 Grade', '2523', 'BAG', '350.00', '500',   '50',  'OPC 53 grade cement'])
        ws.append(['Steel Rod 10mm',      '7214', 'KG',  '75.00',  '1000',  '100', ''])
        ws.append(['PVC Pipe 4 inch',     '3917', 'MTR', '120.00', '200',   '20',  ''])
        ws.append(['Sand (River)',         '2505', 'CFT', '45.00',  '5000',  '500', ''])
        ws.append(['Bricks',              '6901', 'NOS', '8.00',   '10000', '1000','Red bricks'])

        for cell in ws[1]:
            cell.font      = Font(bold=True, color="FFFFFF")
            cell.fill      = PatternFill("solid", fgColor="2563EB")
            cell.alignment = Alignment(horizontal='center')

        for i, width in enumerate([35, 12, 8, 10, 14, 14, 35], 1):
            ws.column_dimensions[ws.cell(1, i).column_letter].width = width

        # Instructions sheet
        ws2 = wb.create_sheet("Instructions")
        ws2.append(["Column",        "Required?", "Notes"])
        ws2.append(["item_name",     "YES",       "Product / item name"])
        ws2.append(["hsn_code",      "No",        "HSN/SAC code for GST. Leave blank if not applicable."])
        ws2.append(["unit",          "No",        "PCS / KG / LTR / MTR / BAG / CFT / NOS etc. Defaults to PCS."])
        ws2.append(["rate",          "No",        "Price per unit. Defaults to 0."])
        ws2.append(["current_stock", "No",        "Opening stock quantity. Defaults to 0."])
        ws2.append(["reorder_level", "No",        "Minimum stock level for reorder alert. Defaults to 0."])
        ws2.append(["description",   "No",        "Any additional notes."])
        ws2.append([])
        ws2.append(["NOTE", "", "item_code is AUTO-GENERATED by the system (e.g. ITEM/0001). Do NOT add it to the sheet."])

        for cell in ws2[1]:
            cell.font = Font(bold=True)
        ws2.column_dimensions['A'].width = 16
        ws2.column_dimensions['B'].width = 12
        ws2.column_dimensions['C'].width = 65

        buffer = BytesIO()
        wb.save(buffer)
        buffer.seek(0)

        response = HttpResponse(
            buffer.getvalue(),
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = 'attachment; filename="product_upload_template.xlsx"'
        return response


class ProductBulkUploadView(APIView):
    """
    POST /api/inventory/products/bulk-upload/
    Body: multipart/form-data   key: "file"   (.xlsx / .xls)

    - item_code is AUTO-GENERATED — do NOT include in Excel
    - item_name is the only required column
    - Every valid row creates a NEW product
    - Rows with errors are skipped; all valid rows are saved

    Response:
    {
        "total_rows": 5,
        "created":    5,
        "skipped":    0,
        "errors":     [],
        "products": [
            {"row": 2, "item_code": "ITEM/2026/0001", "item_name": "Cement OPC 53 Grade"},
            ...
        ]
    }
    """
    permission_classes = [IsAuthenticated]
    parser_classes     = [MultiPartParser]

    def post(self, request):
        file = request.FILES.get('file')

        if not file:
            return Response(
                {'error': 'No file provided. Use form-data with key "file".'},
                status=status.HTTP_400_BAD_REQUEST
            )
        if not file.name.endswith(('.xlsx', '.xls')):
            return Response(
                {'error': 'Only .xlsx or .xls files are accepted.'},
                status=status.HTTP_400_BAD_REQUEST
            )

        try:
            wb = openpyxl.load_workbook(file, data_only=True)
            ws = wb.active
        except Exception:
            return Response(
                {'error': 'Could not read the file. Make sure it is a valid Excel file.'},
                status=status.HTTP_400_BAD_REQUEST
            )

        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            return Response({'error': 'Excel file is empty.'}, status=status.HTTP_400_BAD_REQUEST)

        raw_headers = [
            str(h).strip().lower() if h is not None else ''
            for h in rows[0]
        ]

        if 'item_name' not in raw_headers:
            return Response(
                {'error': 'Missing required column: item_name'},
                status=status.HTTP_400_BAD_REQUEST
            )

        col       = {name: idx for idx, name in enumerate(raw_headers)}
        data_rows = rows[1:]
        created   = 0
        errors    = []
        products  = []

        for row_num, row in enumerate(data_rows, start=2):

            if all(v is None or str(v).strip() == '' for v in row):
                continue

            def get(field):
                idx = col.get(field)
                val = row[idx] if idx is not None and idx < len(row) else None
                return str(val).strip() if val is not None else ''

            item_name = get('item_name')
            hsn_code  = get('hsn_code')
            unit      = get('unit') or 'PCS'
            desc      = get('description')

            row_errors = []

            if not item_name:
                row_errors.append('item_name is required')

            rate = 0
            if get('rate'):
                try:
                    rate = float(get('rate'))
                    if rate < 0:
                        row_errors.append('rate cannot be negative')
                except ValueError:
                    row_errors.append(f'rate "{get("rate")}" is not a valid number')

            current_stock = 0
            if get('current_stock'):
                try:
                    current_stock = float(get('current_stock'))
                    if current_stock < 0:
                        row_errors.append('current_stock cannot be negative')
                except ValueError:
                    row_errors.append(f'current_stock "{get("current_stock")}" is not a valid number')

            reorder_level = 0
            if get('reorder_level'):
                try:
                    reorder_level = float(get('reorder_level'))
                    if reorder_level < 0:
                        row_errors.append('reorder_level cannot be negative')
                except ValueError:
                    row_errors.append(f'reorder_level "{get("reorder_level")}" is not a valid number')

            if row_errors:
                errors.append({
                    'row':       row_num,
                    'item_name': item_name or '(blank)',
                    'error':     ', '.join(row_errors)
                })
                continue

            try:
                # item_code auto-generated inside model.save()
                product = Product.objects.create(
                    item_name     = item_name,
                    hsn_code      = hsn_code,
                    unit          = unit,
                    rate          = rate,
                    current_stock = current_stock,
                    reorder_level = reorder_level,
                    description   = desc,
                )
                created += 1
                products.append({
                    'row':       row_num,
                    'item_code': product.item_code,   # show the generated code
                    'item_name': product.item_name,
                })

            except Exception as e:
                errors.append({
                    'row':       row_num,
                    'item_name': item_name,
                    'error':     str(e)
                })

        non_empty = sum(
            1 for r in data_rows
            if not all(v is None or str(v).strip() == '' for v in r)
        )

        return Response({
            'total_rows': non_empty,
            'created':    created,
            'skipped':    len(errors),
            'errors':     errors,
            'products':   products,
        }, status=status.HTTP_200_OK)
