# Generated by Django 6.0.1 on 2026-06-15 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0010_add_trade_type_to_pi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ti_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('kind', models.CharField(choices=[('PRODUCT', 'Tax Invoice'), ('SERVICE', 'Service Tax Invoice')], default='PRODUCT', max_length=10)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_gstin', models.CharField(blank=True, default='', max_length=50)),
                ('company_pan', models.CharField(blank=True, default='', max_length=50)),
                ('company_iec', models.CharField(blank=True, default='', max_length=50)),
                ('copy_label', models.CharField(blank=True, default='ORIGINAL FOR RECIPIENT', max_length=60)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('challan_no', models.CharField(blank=True, default='', max_length=100)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('state_code', models.CharField(blank=True, default='', max_length=10)),
                ('vendor_code', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=100)),
                ('mode_of_transport', models.CharField(blank=True, default='', max_length=100)),
                ('place_of_supply', models.CharField(blank=True, default='', max_length=300)),
                ('buyers_order_no', models.CharField(blank=True, default='', max_length=200)),
                ('buyers_order_date', models.DateField(blank=True, null=True)),
                ('work_order_no', models.CharField(blank=True, default='', max_length=200)),
                ('bill_to_name', models.CharField(blank=True, default='', max_length=200)),
                ('bill_to_address', models.TextField(blank=True, default='')),
                ('bill_to_gstin', models.CharField(blank=True, default='', max_length=50)),
                ('bill_to_state', models.CharField(blank=True, default='', max_length=100)),
                ('ship_to_name', models.CharField(blank=True, default='', max_length=200)),
                ('ship_to_address', models.TextField(blank=True, default='')),
                ('ship_to_project', models.TextField(blank=True, default='')),
                ('ship_to_state', models.CharField(blank=True, default='', max_length=100)),
                ('total_amount_before_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_amount_after_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('amount_in_words', models.CharField(blank=True, default='', max_length=500)),
                ('gst_on_reverse_charge', models.CharField(blank=True, default='No', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account', models.CharField(blank=True, default='', max_length=100)),
                ('bank_ifsc', models.CharField(blank=True, default='', max_length=50)),
                ('terms_of_payment', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoices', to='sales.proformainvoice')),
            ],
            options={
                'db_table': 'tax_invoices',
                'ordering': ['-ti_number'],
            },
        ),
        migrations.CreateModel(
            name='TaxInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('hs_sac_code', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, default='No.', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('pi_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.proformainvoiceitem')),
                ('tax_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='domestic.taxinvoice')),
            ],
            options={
                'db_table': 'tax_invoice_items',
                'ordering': ['sort_order'],
            },
        ),
    ]
