# Generated by Django 6.0.1 on 2026-06-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0001_initial'),
        ('sales', '0010_add_trade_type_to_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='proforma_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoices', to='sales.proformainvoice'),
        ),
    ]
