# Generated by Django 6.0.1 on 2026-06-16 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0002_alter_taxinvoice_proforma_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20),
        ),
        migrations.CreateModel(
            name='TaxInvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='NEFT', max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('total_paid_after', models.DecimalField(decimal_places=2, max_digits=16)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoice_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('tax_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='domestic.taxinvoice')),
            ],
            options={
                'db_table': 'tax_invoice_payments',
                'ordering': ['tax_invoice', 'payment_number'],
            },
        ),
    ]
