# Generated by Django 6.0.1 on 2026-02-12 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wo_number', models.CharField(help_text='Auto-generated: WO/YEAR/NUMBER or manual input', max_length=50, unique=True)),
                ('wo_date', models.DateField(help_text='Work order date')),
                ('client_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all items before tax', max_digits=12)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal + all taxes', max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total advance received', max_digits=12)),
                ('advance_deducted', models.DecimalField(decimal_places=2, default=0, help_text='Total advance deducted across all bills', max_digits=12)),
                ('advance_remaining', models.DecimalField(decimal_places=2, default=0, help_text='Remaining advance (auto-calculated)', max_digits=12)),
                ('total_delivered_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value delivered across all bills', max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sales_quotation', models.OneToOneField(help_text='Reference sales quotation (one WO per quotation)', on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='sales.salesquotation')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'db_table': 'work_orders',
                'ordering': ['-wo_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(default='PCS', max_length=20)),
                ('ordered_quantity', models.DecimalField(decimal_places=2, help_text='Total quantity ordered', max_digits=10)),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Total quantity delivered across all bills', max_digits=10)),
                ('pending_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Remaining quantity (auto-calculated)', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per unit', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='ordered_quantity × rate', max_digits=12)),
                ('stock_available', models.BooleanField(default=False, help_text='Stock availability at WO creation')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Stock quantity at WO creation', max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Work Order Item',
                'verbose_name_plural': 'Work Order Items',
                'db_table': 'work_order_items',
            },
        ),
    ]
