# Generated by Django 6.0.1 on 2026-05-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_bill_created_by_remove_bill_work_order_and_more'),
        ('work_orders', '0003_remove_workorder_exchange_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderitem',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='workorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
        migrations.DeleteModel(
            name='WorkOrderItem',
        ),
    ]
