# Generated by Django 6.0.1 on 2026-06-06 07:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_product_total_purchased_qty_product_total_sold_qty'),
        ('purchase_orders', '0013_add_payment_due_date'),
        ('sales', '0008_make_requisition_nullable_on_pi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('return_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('debit_note_number', models.CharField(blank=True, default='', max_length=50)),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_returns',
                'ordering': ['-return_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective'), ('WRONG_ITEM', 'Wrong Item'), ('EXCESS', 'Excess Quantity'), ('DAMAGED', 'Damaged in Transit'), ('QUALITY', 'Quality Issue'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('condition', models.CharField(choices=[('GOOD', 'Good — Resalable'), ('DAMAGED', 'Damaged — Needs Repair'), ('UNUSABLE', 'Unusable — Write Off')], default='GOOD', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.purchasereturn')),
            ],
            options={
                'db_table': 'purchase_return_items',
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('return_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('credit_note_number', models.CharField(blank=True, default='', max_length=50)),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns_created', to=settings.AUTH_USER_MODEL)),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='sales.proformainvoice')),
            ],
            options={
                'db_table': 'sales_returns',
                'ordering': ['-return_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective'), ('WRONG_ITEM', 'Wrong Item'), ('EXCESS', 'Excess Quantity'), ('DAMAGED', 'Damaged in Transit'), ('QUALITY', 'Quality Issue'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('condition', models.CharField(choices=[('GOOD', 'Good — Resalable'), ('DAMAGED', 'Damaged — Needs Repair'), ('UNUSABLE', 'Unusable — Write Off')], default='GOOD', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.salesreturn')),
            ],
            options={
                'db_table': 'sales_return_items',
            },
        ),
    ]
