# Generated by Django 6.0.1 on 2026-06-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module',
            field=models.CharField(choices=[('MASTER', 'Master'), ('PURCHASE', 'Purchase'), ('SALES', 'Sales'), ('FINANCE', 'Finance'), ('TRANSPORT', 'Transport')], max_length=20),
        ),
    ]
