# Generated by Django 6.0.1 on 2026-06-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermodulepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module',
            field=models.CharField(choices=[('MASTER', 'Master'), ('PURCHASE', 'Purchase'), ('SALES', 'Sales'), ('FINANCE', 'Finance'), ('TRANSPORT', 'Transport'), ('RETURNS', 'Returns')], max_length=20),
        ),
    ]
