# Generated by Django 6.0.1 on 2026-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(editable=False, help_text='Auto-generated: ITEM/YEAR/NUMBER', max_length=50, unique=True),
        ),
    ]
