# Generated by Django 6.0.1 on 2026-05-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requisition_number',
            field=models.CharField(blank=True, default='', help_text='Requisition number this item belongs to', max_length=50),
        ),
    ]
