# Generated by Django 6.0.1 on 2026-05-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_requisition_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this item has been purchased (received in PO)'),
        ),
    ]
