# Generated by Django 6.0.1 on 2026-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_purchase_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_purchase_date',
            field=models.DateField(blank=True, help_text='Date of last purchase (PO received)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_sale_date',
            field=models.DateField(blank=True, help_text='Date of last sale (PI created/sent)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this item has been sold (via PI)'),
        ),
    ]
