# Generated by Django 6.0.1 on 2026-06-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_sale_count_and_aging_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_purchased_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quantity purchased across all POs', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sold_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quantity sold across all PIs', max_digits=12),
        ),
    ]
