# Generated by Django 6.0.1 on 2026-01-27 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(editable=False, help_text='Auto-generated: VQ/YEAR/NUMBER', max_length=50, unique=True)),
                ('quotation_date', models.DateField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, help_text="Vendor's quotation reference number", max_length=100)),
                ('validity_date', models.DateField(blank=True, help_text='Quotation validity date', null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('delivery_terms', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total quotation amount', max_digits=12)),
                ('is_selected', models.BooleanField(default=False, help_text='Whether this quotation is selected for PO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(help_text='Reference to vendor assignment', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='requisitions.vendorrequisitionassignment')),
                ('created_by', models.ForeignKey(help_text='User who created the quotation', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Quotation',
                'verbose_name_plural': 'Vendor Quotations',
                'db_table': 'vendor_quotations',
                'ordering': ['-quotation_number'],
            },
        ),
        migrations.CreateModel(
            name='VendorQuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quoted_rate', models.DecimalField(decimal_places=2, help_text='Rate quoted by vendor per unit', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='quantity × quoted_rate', max_digits=12)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, help_text='GST/Tax percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='total_price + tax_amount', max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisitions.vendorquotation')),
                ('vendor_item', models.ForeignKey(help_text='Reference to assigned item', on_delete=django.db.models.deletion.PROTECT, to='requisitions.vendorrequisitionitem')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
                'db_table': 'vendor_quotation_items',
            },
        ),
    ]
