# Generated by Django 6.0.1 on 2026-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_vendorquotation_vendorquotationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorquotationitem',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='vendorquotationitem',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='vendorquotationitem',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorquotationitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='vendorquotationitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='quantity × quoted_rate (without tax)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorquotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quotation amount (without tax)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendorquotationitem',
            name='quoted_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate quoted by vendor per unit (without tax)', max_digits=10),
        ),
    ]
