# Generated by Django 6.0.1 on 2026-01-29 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0003_remove_vendorquotationitem_final_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorquotation',
            options={'ordering': ['-quotation_number']},
        ),
        migrations.AddConstraint(
            model_name='vendorquotation',
            constraint=models.UniqueConstraint(fields=('assignment',), name='unique_quotation_per_assignment'),
        ),
    ]
