# Generated by Django 6.0.1 on 2026-05-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0004_alter_vendorquotation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorquotation',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', help_text='Currency in which vendor quoted', max_length=3),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='USD to INR rate at time of quotation (1 if INR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='original_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total in original currency (same as total_amount if INR)', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorquotationitem',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in original currency (same as amount if INR)', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorquotationitem',
            name='original_quoted_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate in original currency (same as quoted_rate if INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendorquotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quotation amount in INR (without tax)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendorquotationitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='quantity × quoted_rate in INR (without tax)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorquotationitem',
            name='quoted_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate quoted by vendor per unit in INR (without tax)', max_digits=10),
        ),
    ]
