# Generated by Django 6.0.1 on 2026-05-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0005_vendorquotation_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorquotationitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='quantity × quoted_rate in INR (without tax)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorquotationitem',
            name='original_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Amount in original currency (same as amount if INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendorquotationitem',
            name='original_quoted_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Rate in original currency (same as quoted_rate if INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendorquotationitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendorquotationitem',
            name='quoted_rate',
            field=models.DecimalField(decimal_places=4, help_text='Rate quoted by vendor per unit in INR (without tax)', max_digits=10),
        ),
    ]
