

# Generated by Django 6.0.1 on 2026-05-11 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0006_allow_decimal_places_in_quotation_items'),
        ('vendors', '0002_vendor_account_name_vendor_swift_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendorrequisitionassignment',
            constraint=models.UniqueConstraint(fields=('requisition', 'vendor'), name='unique_vendor_per_requisition'),
        ),
    ]
