# Generated by Django 6.0.1 on 2026-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0007_unique_vendor_per_requisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorquotation',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='vendorquotation',
            name='original_total_amount',
        ),
        migrations.RemoveField(
            model_name='vendorquotationitem',
            name='original_amount',
        ),
        migrations.RemoveField(
            model_name='vendorquotationitem',
            name='original_quoted_rate',
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_number',
            field=models.CharField(help_text='Manual entry or auto-generated: EEL/YEAR/NUMBER', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorquotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quotation amount (without tax)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendorquotationitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='quantity × quoted_rate (without tax)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorquotationitem',
            name='quoted_rate',
            field=models.DecimalField(decimal_places=4, help_text='Rate quoted by vendor per unit (without tax)', max_digits=10),
        ),
    ]
