# Generated by Django 6.0.1 on 2026-03-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_name',
            field=models.CharField(blank=True, help_text='Name as it appears on the bank account', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='swift_code',
            field=models.CharField(blank=True, help_text='SWIFT/BIC code for international wire transfers', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code for domestic (NEFT/RTGS/IMPS) transfers', max_length=20),
        ),
    ]
