# Generated by Django 6.0.1 on 2026-06-10 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('purchase_orders', '0013_add_payment_due_date'),
        ('sales', '0008_make_requisition_nullable_on_pi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_file', models.ImageField(help_text='PNG or JPG only', upload_to='signatures/%Y/%m/%d/')),
                ('signature_base64', models.TextField(help_text='Base64 encoded signature for easy transmission')),
                ('name', models.CharField(default='Official Signature', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Signature',
                'verbose_name_plural': 'User Signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('content_object_type', models.CharField(choices=[('PI', 'PI'), ('PO', 'PO')], max_length=20)),
                ('signature_position', models.IntegerField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_logs', to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='signatures.usersignature')),
            ],
            options={
                'verbose_name': 'Signature Log',
                'verbose_name_plural': 'Signature Logs',
                'ordering': ['signature_position', 'signed_at'],
            },
        ),
        migrations.CreateModel(
            name='POVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('SELF_VERIFICATION', 'Self Verification'), ('EXTERNAL_VERIFICATION', 'External Verification'), ('CHAIN_VERIFICATION', 'Chain Verification')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('signature_position', models.IntegerField(default=1)),
                ('verification_chain', models.JSONField(default=list, help_text='Array of all signatures in chain')),
                ('verifiers', models.JSONField(default=list, help_text='Array of verifiers with roles and approval status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Deprecated: use verifiers field instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='purchase_orders.purchaseorder')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signatures.usersignature')),
            ],
            options={
                'verbose_name': 'PO Verification',
                'verbose_name_plural': 'PO Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('SELF_VERIFICATION', 'Self Verification'), ('EXTERNAL_VERIFICATION', 'External Verification'), ('CHAIN_VERIFICATION', 'Chain Verification')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('signature_position', models.IntegerField(default=1)),
                ('verification_chain', models.JSONField(default=list, help_text='Array of all signatures in chain')),
                ('verifiers', models.JSONField(default=list, help_text='Array of verifiers with roles and approval status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Deprecated: use verifiers field instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='sales.proformainvoice')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signatures.usersignature')),
            ],
            options={
                'verbose_name': 'PI Verification',
                'verbose_name_plural': 'PI Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('PI_VERIFICATION_REQUESTED', 'PI Verification Requested'), ('PI_VERIFIED', 'PI Verified'), ('PI_REJECTED', 'PI Rejected'), ('PO_VERIFICATION_REQUESTED', 'PO Verification Requested'), ('PO_VERIFIED', 'PO Verified'), ('PO_REJECTED', 'PO Rejected'), ('SIGNATURE_CHAIN_UPDATED', 'Signature Chain Updated')], max_length=50)),
                ('object_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='signatures__user_id_c20b78_idx'), models.Index(fields=['is_read'], name='signatures__is_read_b2c1da_idx')],
            },
        ),
    ]
