# Generated by Django 6.0.1 on 2026-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PI_VERIFICATION_REQUESTED', 'PI Verification Requested'), ('PI_VERIFIED', 'PI Verified'), ('PI_REJECTED', 'PI Rejected'), ('PO_VERIFICATION_REQUESTED', 'PO Verification Requested'), ('PO_VERIFIED', 'PO Verified'), ('PO_REJECTED', 'PO Rejected'), ('SIGNATURE_CHAIN_UPDATED', 'Signature Chain Updated'), ('PI_ITEMS_NOT_PURCHASED', 'PI Items Pending Purchase')], max_length=50),
        ),
    ]
