# Generated by Django 6.0.1 on 2026-06-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PI_VERIFICATION_REQUESTED', 'PI Verification Requested'), ('PI_VERIFIED', 'PI Verified'), ('PI_REJECTED', 'PI Rejected'), ('PO_VERIFICATION_REQUESTED', 'PO Verification Requested'), ('PO_VERIFIED', 'PO Verified'), ('PO_REJECTED', 'PO Rejected'), ('SIGNATURE_CHAIN_UPDATED', 'Signature Chain Updated'), ('PI_ITEMS_NOT_PURCHASED', 'PI Items Pending Purchase'), ('REQUISITION_CREATED', 'Requisition Created'), ('PURCHASE_ORDER_CREATED', 'Purchase Order Created'), ('PI_CREATED', 'Proforma Invoice Created'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('ADVANCE_PAYMENT_RECORDED', 'Advance Payment Recorded'), ('TRANSPORT_CREATED', 'Transport Entry Created'), ('SALES_RETURN_CREATED', 'Sales Return Created'), ('PURCHASE_RETURN_CREATED', 'Purchase Return Created')], max_length=50),
        ),
    ]
