# Generated by Django 6.0.1 on 2026-05-22 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_orders', '0007_remove_purchaseorder_freight_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('transporter_name', models.CharField(max_length=200)),
                ('transporter_contact', models.CharField(blank=True, max_length=50)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('driver_contact', models.CharField(blank=True, max_length=50)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('dispatch_from', models.CharField(blank=True, max_length=300)),
                ('dispatch_to', models.CharField(blank=True, max_length=300)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated sum of all cost items', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_entries', to='purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'transport_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportCostItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_type', models.CharField(choices=[('FREIGHT', 'Freight Charges'), ('LOADING', 'Loading Charges'), ('UNLOADING', 'Unloading Charges'), ('INSURANCE', 'Insurance'), ('CUSTOMS', 'Customs Duty'), ('OCTROI', 'Octroi / Entry Tax'), ('HANDLING', 'Handling Charges'), ('PACKAGING', 'Packaging Charges'), ('TOLL', 'Toll Charges'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('transport_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='transport.transportentry')),
            ],
            options={
                'db_table': 'transport_cost_items',
            },
        ),
    ]
