# Generated by Django 6.0.1 on 2026-05-25 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0013_add_payment_due_date'),
        ('sales', '0006_add_gst_discount_conversion_to_pi'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportentry',
            name='proforma_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_entries', to='sales.proformainvoice'),
        ),
        migrations.AlterField(
            model_name='transportentry',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_entries', to='purchase_orders.purchaseorder'),
        ),
    ]
