# Generated by Django 6.0.1 on 2026-06-17 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_total_purchased_qty_product_total_sold_qty'),
        ('purchase_orders', '0013_add_payment_due_date'),
        ('sales', '0010_add_trade_type_to_pi'),
        ('transport', '0002_add_pi_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportentry',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='invoice_reference',
            field=models.CharField(blank=True, help_text="Transporter's invoice / bilty number", max_length=100),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='lr_number',
            field=models.CharField(blank=True, help_text='Lorry Receipt / Consignment note number', max_length=100),
        ),
        migrations.AddField(
            model_name='transportentry',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
        migrations.CreateModel(
            name='TransportConsignmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('pi_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_items', to='sales.proformainvoiceitem')),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_items', to='purchase_orders.purchaseorderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('transport_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_items', to='transport.transportentry')),
            ],
            options={
                'db_table': 'transport_consignment_items',
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transporter_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=30)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transporters',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transportentry',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_entries', to='transport.transporter'),
        ),
        migrations.CreateModel(
            name='TransportPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(editable=False, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('TT', 'Telegraphic Transfer'), ('OTHER', 'Other')], default='NEFT', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('total_paid_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('transport_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transport.transportentry')),
            ],
            options={
                'db_table': 'transport_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
