# Generated by Django 6.0.1 on 2026-06-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_backfill_transport_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportpayment',
            name='payment_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
