# Generated by Django 6.0.1 on 2026-03-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_purchaseorder_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Freight / shipping cost added on top of item total', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='items_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line-item amounts (qty × rate)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='items_total + freight_cost', max_digits=12),
        ),
    ]
