# Generated by Django 6.0.1 on 2026-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_purchaseorder_freight_cost_purchaseorder_items_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid to vendor (sum of all PurchasePayment rows, INR)', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance (total_amount - amount_paid, INR)', max_digits=12),
        ),
    ]
