# Generated by Django 6.0.1 on 2026-05-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0004_purchaseorder_amount_paid_purchaseorder_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', help_text='Currency inherited from vendor quotation', max_length=3),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='USD to INR rate at time of PO (1 if INR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='original_freight_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Freight cost in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='original_items_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Items total in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='original_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='original_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate in original currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate in INR', max_digits=10),
        ),
    ]
