# Generated by Django 6.0.1 on 2026-05-22 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0005_purchaseorder_currency_purchaseorder_exchange_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='original_freight_cost',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='original_items_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='original_total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='original_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='original_rate',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cgst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='igst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_revised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when PO was locked for editing', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this PO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='revision_number',
            field=models.PositiveIntegerField(default=0, help_text='Incremented on each edit; 0 = original'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sgst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='items_total + freight_cost + GST', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='quantity × rate', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate per unit', max_digits=10),
        ),
    ]
