# Generated by Django 6.0.1 on 2026-05-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0006_remove_purchaseorder_exchange_rate_and_more'),
        ('requisitions', '0008_remove_vendorquotation_exchange_rate_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='purchaseorder',
                    name='freight_cost',
                ),
                migrations.AlterField(
                    model_name='purchaseorder',
                    name='total_amount',
                    field=models.DecimalField(decimal_places=2, default=0, help_text='items_total + GST', max_digits=12),
                ),
                migrations.AlterField(
                    model_name='purchaseorderitem',
                    name='quotation_item',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='requisitions.vendorquotationitem'),
                ),
            ],
            database_operations=[
                # All DB changes were already applied by the partially-failed first attempt:
                # - freight_cost column dropped
                # - total_amount help_text changed (no actual DB impact)
                # - quotation_item_id already made nullable
            ],
        ),
    ]
