# Generated by Django 6.0.1 on 2026-05-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0007_remove_purchaseorder_freight_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='INR conversion rate at the time of PO creation (for record only, no conversion applied)', max_digits=10, null=True),
        ),
    ]
