# Generated by Django 6.0.1 on 2026-05-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0008_purchaseorder_conversion_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Vendor discount amount (in PO currency), subtracted from total', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='items_total + GST - discount', max_digits=12),
        ),
    ]
