# Generated by Django 6.0.1 on 2026-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0009_purchaseorder_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
