# Generated by Django 6.0.1 on 2026-05-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0010_purchaseorder_project_name_purchaseorder_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to',
            field=models.TextField(blank=True, default=''),
        ),
    ]
