# Generated by Django 6.0.1 on 2026-05-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0011_purchaseorder_bill_to_purchaseorder_ship_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='terms_and_conditions',
            field=models.JSONField(blank=True, default=list, help_text='Array of terms & conditions'),
        ),
    ]
