# Generated by Django 6.0.1 on 2026-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0012_purchaseorder_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Payment due date to vendor', null=True),
        ),
    ]
