# Generated by Django 6.0.1 on 2026-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0013_add_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, help_text='Auto-generated (EEL/IND/<VENDOR>/<n>) when left blank; can be overridden while editing.', max_length=50, unique=True),
        ),
    ]
