# Generated by Django 6.0.1 on 2026-02-06 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_number', models.CharField(editable=False, help_text='Auto-generated: CQ/YEAR/NUMBER', max_length=50, unique=True)),
                ('client_name', models.CharField(help_text='Client/Customer name', max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('query_date', models.DateField(help_text='Date of query received')),
                ('pdf_file', models.CharField(blank=True, help_text='Path to uploaded PDF file in container', max_length=500)),
                ('remarks', models.TextField(blank=True, help_text='Query details and remarks')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUOTATION_SENT', 'Quotation Sent'), ('CONVERTED', 'Converted to Sale'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_queries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Query',
                'verbose_name_plural': 'Client Queries',
                'db_table': 'client_queries',
                'ordering': ['-query_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(editable=False, help_text='Auto-generated: SQ/YEAR/NUMBER', max_length=50, unique=True)),
                ('quotation_date', models.DateField(help_text='Date of quotation')),
                ('validity_date', models.DateField(blank=True, help_text='Valid until date', null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('delivery_terms', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0, help_text='CGST percentage', max_digits=5)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0, help_text='SGST percentage', max_digits=5)),
                ('igst_percentage', models.DecimalField(decimal_places=2, default=0, help_text='IGST percentage (for interstate)', max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all items before tax', max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal + all taxes', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Client'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.clientquery')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Quotation',
                'verbose_name_plural': 'Sales Quotations',
                'db_table': 'sales_quotations',
                'ordering': ['-quotation_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, help_text='Item code (auto-filled from product or manual)', max_length=50)),
                ('item_name', models.CharField(help_text='Item name (auto-filled from product or manual)', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(default='PCS', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per unit', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='quantity × rate', max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('product', models.ForeignKey(blank=True, help_text='Product from inventory (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesquotation')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
                'db_table': 'sales_quotation_items',
            },
        ),
    ]
