# Generated by Django 6.0.1 on 2026-05-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', help_text='Currency for this quotation', max_length=3),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='USD to INR rate at time of quotation (1 if INR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='original_cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='original_igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='original_sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='original_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='original_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total in original currency', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesquotationitem',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in original currency (same as amount if INR)', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesquotationitem',
            name='original_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate in original currency (same as rate if INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal + all taxes (INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesquotationitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='quantity × rate (INR)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesquotationitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate per unit (INR)', max_digits=10),
        ),
    ]
