# Generated by Django 6.0.1 on 2026-05-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesquotation_currency_salesquotation_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquery',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', help_text='Currency in which the client wants to deal (INR or USD)', max_length=3),
        ),
    ]
