# Generated by Django 6.0.1 on 2026-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_clientquery_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesquotation',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='original_cgst_amount',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='original_igst_amount',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='original_sgst_amount',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='original_subtotal',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='original_total_amount',
        ),
        migrations.RemoveField(
            model_name='salesquotationitem',
            name='original_amount',
        ),
        migrations.RemoveField(
            model_name='salesquotationitem',
            name='original_rate',
        ),
        migrations.AlterField(
            model_name='salesquotationitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='quantity × rate', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesquotationitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate per unit', max_digits=10),
        ),
    ]
