# Generated by Django 6.0.1 on 2026-05-25 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_purchase_count'),
        ('requisitions', '0008_remove_vendorquotation_exchange_rate_and_more'),
        ('sales', '0004_remove_salesquotation_exchange_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pi_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('pi_date', models.DateField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('lc_number', models.CharField(blank=True, default='', max_length=100)),
                ('exporter_beneficiary', models.TextField(blank=True, default='')),
                ('exporter_reference', models.CharField(blank=True, default='', max_length=200)),
                ('gst_number', models.CharField(blank=True, default='', max_length=50)),
                ('consignee', models.TextField(blank=True, default='')),
                ('applicant_importer', models.TextField(blank=True, default='')),
                ('pre_carriage_by', models.CharField(blank=True, default='', max_length=200)),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=100)),
                ('final_destination', models.CharField(blank=True, default='', max_length=200)),
                ('place_of_receipt', models.CharField(blank=True, default='', max_length=200)),
                ('port_of_loading', models.CharField(blank=True, default='', max_length=200)),
                ('port_of_discharge', models.CharField(blank=True, default='', max_length=200)),
                ('terms_of_delivery', models.CharField(blank=True, default='', max_length=200)),
                ('terms_of_payment', models.CharField(blank=True, default='', max_length=200)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('terms_and_conditions', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('is_revised', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_proforma_invoices', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='requisitions.requisition')),
            ],
            options={
                'db_table': 'proforma_invoices',
                'ordering': ['-pi_number'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.proformainvoice')),
                ('requisition_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='requisitions.requisitionitem')),
            ],
            options={
                'db_table': 'proforma_invoice_items',
            },
        ),
    ]
