# Generated by Django 6.0.1 on 2026-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_proformainvoice_proformainvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='cgst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='INR conversion rate at PI creation (immutable record)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount subtracted from total', max_digits=12),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='igst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Payment due date from client', null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='sgst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of items before tax', max_digits=12),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='subtotal + GST - discount', max_digits=12),
        ),
    ]
