# Generated by Django 6.0.1 on 2026-05-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_gst_discount_conversion_to_pi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformainvoice',
            name='cgst_amount',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='cgst_percentage',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='igst_amount',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='igst_percentage',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='sgst_amount',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='sgst_percentage',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all items', max_digits=12),
        ),
    ]
