# Generated by Django 6.0.1 on 2026-06-06 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0008_remove_vendorquotation_exchange_rate_and_more'),
        ('sales', '0007_remove_gst_discount_from_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoice',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='requisitions.requisition'),
        ),
    ]
