# Generated by Django 6.0.1 on 2026-07-02 11:46

import django.db.models.deletion
from django.db import migrations, models


def backfill_requisitions(apps, schema_editor):
    """Seed the new M2M with each existing PI's single requisition."""
    ProformaInvoice = apps.get_model('sales', 'ProformaInvoice')
    for pi in ProformaInvoice.objects.exclude(requisition__isnull=True).iterator():
        pi.requisitions.add(pi.requisition_id)


def reverse_backfill(apps, schema_editor):
    ProformaInvoice = apps.get_model('sales', 'ProformaInvoice')
    for pi in ProformaInvoice.objects.iterator():
        pi.requisitions.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0008_remove_vendorquotation_exchange_rate_and_more'),
        ('sales', '0010_add_trade_type_to_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='requisitions',
            field=models.ManyToManyField(blank=True, help_text='All requisitions this PI draws billable items from (mixed parties allowed).', related_name='proforma_invoices_multi', to='requisitions.requisition'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='requisition',
            field=models.ForeignKey(blank=True, help_text='Primary requisition (first selected). Full set is in `requisitions`.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='requisitions.requisition'),
        ),
        migrations.RunPython(backfill_requisitions, reverse_backfill),
    ]
