# Generated by Django 6.0.1 on 2026-07-02 12:54

from django.db import migrations, models


def backfill_unit(apps, schema_editor):
    """Seed each existing PI item's unit from its product."""
    ProformaInvoiceItem = apps.get_model('sales', 'ProformaInvoiceItem')
    for item in ProformaInvoiceItem.objects.select_related('product').iterator():
        unit = (item.product.unit or '') if item.product_id else ''
        if unit and item.unit != unit:
            item.unit = unit
            item.save(update_fields=['unit'])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_proformainvoice_requisitions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unit of measure (editable per PI line; defaults to product unit)', max_length=20),
        ),
        migrations.RunPython(backfill_unit, reverse_backfill),
    ]
