# Generated by Django 6.0.1 on 2026-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_proformainvoiceitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='checked_by',
            field=models.CharField(blank=True, default='', help_text="Name/designation for the 'Checked By' signature block", max_length=150),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='negotiated_by',
            field=models.CharField(blank=True, default='', help_text="Name/designation for the 'Negotiated By' signature block", max_length=150),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='profit_loading_percent',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Profit loading % applied on ex-works purchase price in the Note Sheet', max_digits=6),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='project_name',
            field=models.CharField(blank=True, default='', help_text='Project name shown on the internal Note Sheet', max_length=200),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='export_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Export cost for this line (Note Sheet)', max_digits=12),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Freight cost for this line (Note Sheet)', max_digits=12),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='last_lc_reference',
            field=models.CharField(blank=True, default='', help_text='Last supply LC No & Date (Note Sheet comparison)', max_length=200),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='last_unit_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Last supply unit price (Note Sheet comparison)', max_digits=12),
        ),
    ]
