# Generated by Django 6.0.1 on 2026-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_proformainvoice_checked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='freight_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total freight charges (in PI currency). If > 0, shown on the PI PDF grand-total line.', max_digits=12),
        ),
    ]
