# Generated by Django 6.0.1 on 2026-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_proformainvoice_freight_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='vendor_offers',
            field=models.JSONField(blank=True, default=dict, help_text='Per-vendor offer-rate overrides for the Note Sheet, keyed by vendor name: {"<vendor>": <rate>}. Overrides the rate pulled from vendor quotations for that vendor.'),
        ),
    ]
