# Generated by Django 6.0.1 on 2026-06-15 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0010_add_trade_type_to_pi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ci_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('exporters_ref', models.CharField(blank=True, default='', max_length=200)),
                ('gst_no', models.CharField(blank=True, default='', max_length=50)),
                ('buyers_order_no', models.CharField(blank=True, default='', max_length=100)),
                ('buyers_order_date', models.DateField(blank=True, null=True)),
                ('exporter', models.TextField(blank=True, default='')),
                ('consigned_to_order_of', models.TextField(blank=True, default='')),
                ('importer_notify_party', models.TextField(blank=True, default='')),
                ('applicant', models.TextField(blank=True, default='')),
                ('terms_of_delivery', models.TextField(blank=True, default='')),
                ('terms_of_delivery_and_payment', models.TextField(blank=True, default='')),
                ('place_of_supply', models.CharField(blank=True, default='', max_length=200)),
                ('vessel_flight_no', models.CharField(blank=True, default='', max_length=200)),
                ('port_of_loading', models.CharField(blank=True, default='', max_length=200)),
                ('port_of_discharge', models.CharField(blank=True, default='', max_length=200)),
                ('place_of_delivery', models.CharField(blank=True, default='', max_length=200)),
                ('pre_carriage_by', models.CharField(blank=True, default='', max_length=200)),
                ('place_of_receipt', models.CharField(blank=True, default='', max_length=200)),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=100)),
                ('final_destination', models.CharField(blank=True, default='', max_length=200)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('total_fca_value', models.DecimalField(decimal_places=2, default=0, help_text='Sum of item totals', max_digits=14)),
                ('total_freight', models.DecimalField(decimal_places=2, default=0, help_text='Freight charge (user input)', max_digits=14)),
                ('total_cpt_value', models.DecimalField(decimal_places=2, default=0, help_text='FCA + Freight', max_digits=14)),
                ('amount_in_words', models.CharField(blank=True, default='', max_length=400)),
                ('project_name', models.TextField(blank=True, default='')),
                ('declarations', models.JSONField(blank=True, default=list)),
                ('lut_no', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('proforma_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoices', to='sales.proformainvoice')),
            ],
            options={
                'db_table': 'commercial_invoices',
                'ordering': ['-ci_number'],
            },
        ),
        migrations.CreateModel(
            name='CommercialInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_nos', models.CharField(blank=True, default='', max_length=200)),
                ('no_kind_pkgs', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('hs_code', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, default='Nos.', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('commercial_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commercial.commercialinvoice')),
                ('pi_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.proformainvoiceitem')),
            ],
            options={
                'db_table': 'commercial_invoice_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pl_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('packing_specification', models.TextField(blank=True, default='')),
                ('lut_no', models.CharField(blank=True, default='', max_length=200)),
                ('total_nett_weight', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_gross_weight', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists', to='commercial.commercialinvoice')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'packing_lists',
                'ordering': ['-pl_number'],
            },
        ),
        migrations.CreateModel(
            name='PackingListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_nos', models.CharField(blank=True, default='', max_length=200)),
                ('no_kind_pkgs', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, default='Nos.', max_length=20)),
                ('nett_weight', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('ci_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.commercialinvoiceitem')),
                ('packing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commercial.packinglist')),
            ],
            options={
                'db_table': 'packing_list_items',
                'ordering': ['sort_order'],
            },
        ),
    ]
