# Generated by Django 6.0.1 on 2026-06-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglistitem',
            name='hs_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
