# Generated by Django 6.0.1 on 2026-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_packinglistitem_hs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoice',
            name='marks_from',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='commercialinvoice',
            name='marks_to',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
